comm:
  channel_count: 40
  gamma_alpha: 2.0
  gamma_beta: 2.0
  bandwidth_hz: 1.0e6
  backhaul_bandwidth_hz: 5.0e6
  carrier_hz: 2.4e9
  noise_power: 1.0e-10
  backhaul_noise_power: 1.0e-10
  p_min_w: 0.05
  p_max_w: 1.0
  power_mode: max
  p_fixed_w: 0.5
  backhaul_power_w: 2.0
  round_trip_factor: 2.0
  enable_los: true
  los_model: paper
  path_loss_model: paper
  los_zeta_clear: 1.0
  los_zeta_blocked: 5.0
  los_a: 9.61
  los_b: 0.16
  los_c: 0.0
  los_loss_db: 1.0
  nlos_loss_db: 20.0
  ref_loss_db: 30.0
  path_loss_exp: 2.2
  los_blocked_factor: 0.1
  los_check_step_m: 20.0
  interference_power: 0.0
  interference_mode: fixed
  interference_scale: 1.0
  light_speed: 3.0e8
  channel_mode: gamma
  channel_rounding: fractional
  channel_min: 0
