control:
  mode: pid
  pos_kp: 0.8
  pos_ki: 0.0
  pos_kd: 0.5
  att_kp: 3.5
  att_ki: 0.0
  att_kd: 0.9
  yaw_kp: 2.5
  yaw_ki: 0.0
  yaw_kd: 0.6
  max_tilt_deg: 45.0
  vel_damping: 0.5
  fear_model_path: ""
  fear_scales: [0.7, 0.9, 1.0, 1.1, 1.3]
  fear_kp_min: 0.0
  fear_kp_max: 5.0
  fear_ki_min: 0.0
  fear_ki_max: 1.5
  fear_kd_min: 0.0
  fear_kd_max: 2.5
  integral_limit: 5.0
  fear_action_grid_kp: [-0.2, 0.0, 0.2]
  fear_action_grid_ki: [-0.05, 0.0, 0.05]
  fear_action_grid_kd: [-0.1, 0.0, 0.1]
  fear_action_deltas: []
